# Generated by Django 2.0.2 on 2018-03-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_paradigm_programmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='language',
            new_name='languages',
        ),
        migrations.AlterField(
            model_name='language',
            name='paradigm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Paradigm'),
        ),
    ]
